[workspace]
resolver = "2"
members = [
    "0x434C49434B",
    "gift_shop", 
    "gift_shop_twice", 
    "joltage", 
    "kitchen", 
    "laboratories", 
    "lobby",
    "password_puzzle", 
    "printing_department",
    "roll_paper", "trash-compactor",
]
